# Generated by Django 3.1.6 on 2021-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(verbose_name='Порядковый номер'),
        ),
    ]
