# Generated by Django 3.1.6 on 2021-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20210225_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='places',
                                    verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.PositiveBigIntegerField(blank=True, default=0,
                                                 null=True,
                                                 verbose_name='Порядковый '
                                                              'номер'),
        ),
    ]
